# Generated by Django 3.2.5 on 2021-07-27 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacas', '0002_auto_20210724_0046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaca',
            name='tiempo_preñez',
        ),
    ]
