# Generated by Django 3.1.1 on 2021-08-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacas', '0004_auto_20210811_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaca',
            name='processm',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Muerte', 'Muerte')], max_length=20, null=True),
        ),
    ]
