# Generated by Django 3.1.1 on 2021-08-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacas', '0005_vaca_processm'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaca',
            name='fecha_processm',
            field=models.DateField(null=True),
        ),
    ]
