# Generated by Django 3.1.1 on 2021-08-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacas', '0007_vaca_alimentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaca',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
