# Generated by Django 3.2.5 on 2021-08-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacas', '0010_auto_20210823_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
