# Generated by Django 3.2.5 on 2021-08-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacas', '0011_raza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raza',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
