# Generated by Django 3.2.5 on 2021-07-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preñez', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toro',
            fields=[
                ('metodopreñez_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preñez.metodopreñez')),
                ('nombre', models.CharField(max_length=45)),
                ('raza', models.CharField(max_length=45)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('fecha_compra', models.DateField()),
                ('fecha_primer_monta', models.DateField()),
                ('estado', models.CharField(max_length=45)),
                ('motivo_estado', models.CharField(max_length=255)),
                ('foto', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('preñez.metodopreñez',),
        ),
    ]
