# Generated by Django 3.2.5 on 2021-07-24 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('toros', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toro',
            name='edad',
        ),
        migrations.AddField(
            model_name='toro',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='toro',
            name='foto',
            field=models.TextField(null=True),
        ),
    ]
