# Generated by Django 3.1.5 on 2021-08-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toros', '0002_auto_20210724_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='toro',
            name='costo',
            field=models.FloatField(null=True),
        ),
    ]
