# Generated by Django 3.1.1 on 2021-08-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toros', '0003_toro_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='toro',
            name='processm',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Muerte', 'Muerte')], max_length=20, null=True),
        ),
    ]
