# Generated by Django 3.1.1 on 2021-08-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toros', '0004_toro_processm'),
    ]

    operations = [
        migrations.AddField(
            model_name='toro',
            name='fecha_processm',
            field=models.DateField(null=True),
        ),
    ]
