# Generated by Django 3.1.1 on 2021-08-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toros', '0007_remove_toro_alimentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='toro',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
