# Generated by Django 3.1.1 on 2021-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuarioinfo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarioinfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
