# Generated by Django 3.2.5 on 2021-07-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('vacas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPreñez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_preñez.metodopreñez_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Preñez',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_preñez', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecundaciones', models.ManyToManyField(related_name='fecundaciones', to='preñez.MetodoPreñez')),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacas.vaca')),
            ],
        ),
    ]
