# Generated by Django 3.2.5 on 2021-07-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crias', '0003_cria_vaca_madura_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cria',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
