# Generated by Django 3.1.5 on 2021-08-13 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crias', '0005_auto_20210811_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='cria',
            name='raza',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
