# Generated by Django 3.1.1 on 2021-08-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0003_auto_20210811_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='produccion',
            name='estimación_de_calidad',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
