# Generated by Django 3.2.5 on 2021-07-30 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='fecha_salida',
            field=models.DateField(null=True),
        ),
    ]
