# Generated by Django 3.2.5 on 2021-07-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('cantidad', models.FloatField()),
                ('costo', models.FloatField()),
                ('fecha_suministro', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vaca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vacas.vaca')),
            ],
        ),
    ]
