# Generated by Django 3.1.5 on 2021-08-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0005_auto_20210813_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
    ]
