# Generated by Django 3.1.5 on 2021-08-13 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alimento', '0007_auto_20210813_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimentoexport',
            name='alimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='alimento.alimento'),
        ),
    ]
